Mark 'old' checkout command as obsolete
This commit marks 'bst checkout' as a 'hidden' command. If used,
the user will be prompted to use the new 'bst artifact checkout'
command.

All tests which used 'bst checkout' have been modified to use
the new artifact sub-command.

This partially solves #822.

diff --git a/contrib/bst-docker-import b/contrib/bst-docker-import
--- a/contrib/bst-docker-import
+++ b/contrib/bst-docker-import
@@ -90,7 +90,7 @@ element="$1"
 checkout_tar="bst-checkout-$(basename "$element")-$RANDOM.tar"
 
 echo "INFO: Checking out $element ..." >&2
-$bst_cmd checkout --tar "$element" "$checkout_tar" || die "Failed to checkout $element"
+$bst_cmd artifact checkout "$element" --tar "$checkout_tar" || die "Failed to checkout $element"
 echo "INFO: Successfully checked out $element" >&2
 
 echo "INFO: Importing Docker image ..." >&2
